baseURL = 'https://blog.cocl2.com'
languageCode = 'en-us'
title = "COCl2's blog home"

theme = ["github.com/nanxiaobei/hugo-paper"]

[module]
  [module.hugoVersion]
    min = "0.154.5"
    extended = true

  [[module.imports]]
  path = "github.com/hugomods/images"

  [[module.imports]]
  path = "github.com/hugomods/plausible-analytics"

[markup]
[markup.highlight]
style = "catppuccin-latte"

[params]
color = 'linen'

twitter = "zty0826"
github = "TennyZhuang"
rss = true

math = true

[params.giscus]
repo = 'TennyZhuang/blog-cocl2'                 # see https://giscus.app for more details
repoId = 'R_kgDOLOEHYw'
category = 'Announcements'
categoryId = 'DIC_kwDOLOEHY84Cc84b'
mapping = 'pathname'
theme = 'preferred_color_scheme'
lang = 'en'

[params.plausible_analytics]
  endpoint = "https://plausible.io"
